### ISSUE TITLE
Export JSON NOT VALIDATED in version 1.9.3

### ISSUE THREAD

**Issue by angrysumit94** [litixsoft/mongo-management-studio-localization#7]
Exporting a collection as JSON file in Mongo Management Studio is not giving validated file. What I mean to say is every document is not getting separated using commas. 

![invalid_json](https://cloud.githubusercontent.com/assets/13677055/12973711/61fa4bbc-d0d4-11e5-904c-7c606889f04e.png)

Please tell me how to export it correctly as this is a very huge file and would take hours to add commas in JSON file.
**NOTE-** I do not have admin rights to remote mongodb server so I can not use *_mongoexport *_ command

**Comment by LitixThomas** [comment]
Hi,

thats correct, the exported file is equal to mongoexport and mongoimport generated json files. There are not comma seperated json documents. I'm sorry, there is currently no method to export json in your specified format with mongo management studio.

Thomas

**Comment by angrysumit94** [comment]
Thank you Thomas for your response. 
May I know for what specific usecase MMS exports with this format ( it is just a appended object string )

**Comment by LitixThomas** [comment]
So you have the possibility to use mongoimport.

We will think about, to offer more export formats in a future version.
